workflows:
  hello-hari-phase2:
    name: Hello Hari Android - Phase 2 Audio Recording
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.hellohari"
      node: 18.17.1
      java: 11
    scripts:
      - name: Set up Android environment
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          
      - name: Exclude React Native modules (Phase 2 - Pure Android)
        script: |
          mkdir -p temp_excluded
          mv android/app/src/main/java/com/hellohari/CallDetectorModule.java temp_excluded/ || true
          mv android/app/src/main/java/com/hellohari/PermissionModule.java temp_excluded/ || true
          mv android/app/src/main/java/com/hellohari/CallDetectorPackage.java temp_excluded/ || true
          mv android/app/src/main/java/com/hellohari/AudioRecorderModule.java temp_excluded/ || true
          
      - name: Set Android SDK permissions
        script: |
          cd android && chmod +x gradlew
          
      - name: Create debug keystore
        script: |
          if [ ! -f android/app/debug.keystore ]; then
            keytool -genkeypair -v -keystore android/app/debug.keystore \
              -storepass android -alias androiddebugkey -keypass android \
              -keyalg RSA -keysize 2048 -validity 10000 \
              -dname "CN=Android Debug,O=Android,C=US"
          fi
          
      - name: Build Phase 2 APK with Audio Recording
        script: |
          echo "=== BUILDING HELLO HARI PHASE 2 - AUDIO RECORDING ==="
          cd android
          ./gradlew clean assembleDebug assembleRelease
          
          echo "=== FINDING AND COPYING APK FILES ==="
          find app/build/outputs -name "*.apk" -type f
          
          # Copy APK files with Phase 2 naming
          cp app/build/outputs/apk/debug/app-debug.apk ../HelloHari-Phase2-debug.apk || echo "Debug APK not found"
          cp app/build/outputs/apk/release/app-release.apk ../HelloHari-Phase2-release.apk || echo "Release APK not found"
          
          echo "=== PHASE 2 APK FILES READY ==="
          ls -la ../HelloHari-Phase2*.apk || echo "No APK files copied"
          
    artifacts:
      - HelloHari-Phase2-debug.apk
      - HelloHari-Phase2-release.apk
      - android/app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true
