workflows:
  hello-hari-workflow:
    name: Hello Hari Android
    max_build_duration: 60
    environment:
      android_signing:
        - debug_keystore
      node: latest
      npm: latest
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set Gradle permissions
        script: |
          cd android
          chmod +x gradlew
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
