workflows:
  hello-hari-workflow:
    name: Hello Hari Android - Phase 1 Call Detection
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.hellohari"
      node: 18.17.1
      java: 11
    cache:
      cache_paths:
        - ~/.gradle/caches
        - android/.gradle
    scripts:
      - name: Set up Android environment
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          
      - name: Exclude React Native modules (keeping SimpleCallDetector)
        script: |
          # Move React Native dependent files out of build path
          mkdir -p temp_excluded
          mv android/app/src/main/java/com/hellohari/CallDetectorModule.java temp_excluded/ || true
          mv android/app/src/main/java/com/hellohari/PermissionModule.java temp_excluded/ || true
          mv android/app/src/main/java/com/hellohari/CallDetectorPackage.java temp_excluded/ || true
          mv android/app/src/main/java/com/hellohari/AudioRecorderModule.java temp_excluded/ || true
          echo "Phase 1: Excluded React Native modules, keeping SimpleCallDetector"
          
      - name: Set Android SDK permissions
        script: |
          cd android
          chmod +x gradlew
          
      - name: Create debug keystore
        script: |
          if [ ! -f android/app/debug.keystore ]; then
            keytool -genkeypair -v -keystore android/app/debug.keystore \
              -storepass android -alias androiddebugkey -keypass android \
              -keyalg RSA -keysize 2048 -validity 10000 \
              -dname "CN=Android Debug,O=Android,C=US"
          fi
          
      - name: Build Android APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace
          echo "✅ Phase 1 APK built with call detection functionality"
          
      - name: List and verify APK files
        script: |
          echo "=== APK FILE VERIFICATION ==="
          find android/app/build/outputs -name "*.apk" -type f
          ls -la android/app/build/outputs/apk/debug/ || echo "Debug APK directory not found"
          ls -la android/app/build/outputs/apk/release/ || echo "Release APK directory not found"
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - your.email@example.com # Replace with your email
        notify:
          success: true
          failure: true
