workflows:
  hello-hari-workflow:
    name: Hello Hari Android
    max_build_duration: 60
    environment:
      vars:
        STORE_PASSWORD: "android"
        KEY_PASSWORD: "android"
        KEY_ALIAS: "androiddebugkey"
      node: 18.17.1
    scripts:
      - name: Create React Native project
        script: |
          npm uninstall -g react-native-cli
          npm install -g @react-native-community/cli
          npx react-native init HelloHari --version 0.72.6
          cp -r HelloHari/* .
          rm -rf HelloHari
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Create debug keystore
        script: |
          keytool -genkeypair -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          mv debug.keystore android/app/debug.keystore
      - name: Set Gradle permissions
        script: |
          cd android
          chmod +x gradlew
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/**/*.apk
