workflows:
  hello-hari-workflow:
    name: Hello Hari Android
    max_build_duration: 60
    environment:
      vars:
        STORE_PASSWORD: "android"
        KEY_PASSWORD: "android"
        KEY_ALIAS: "androiddebugkey"
      node: 18.17.1
    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
          npm install -g react-native-cli
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Create debug keystore
        script: |
          keytool -genkeypair -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          mv debug.keystore android/app/debug.keystore
      - name: Set Gradle permissions
        script: |
          cd android
          chmod +x gradlew
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon
          
    artifacts:
      - android/app/build/outputs/**/*.apk
