workflows:
  hello-hari-workflow:
    name: Hello Hari Android
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.hellohari"
      node: 18.17.1
      java: 11
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.npm
        - android/.gradle
        - node_modules
    scripts:
      - name: Set up Android environment
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
          
      - name: Set Android SDK permissions
        script: |
          cd android
          chmod +x gradlew
          
      - name: Create debug keystore
        script: |
          if [ ! -f android/app/debug.keystore ]; then
            keytool -genkeypair -v -keystore android/app/debug.keystore \
              -storepass android -alias androiddebugkey -keypass android \
              -keyalg RSA -keysize 2048 -validity 10000 \
              -dname "CN=Android Debug,O=Android,C=US"
          fi
          
      - name: Gradle clean and build
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease --stacktrace
          
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
      
    publishing:
      email:
        recipients:
          - your.email@example.com # Replace with your email
        notify:
          success: true
          failure: true
