workflows:
  hello-hari-workflow:
    name: Hello Hari Android
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.hellohari"
      node: 18.17.1
      java: 11
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.npm
        - android/.gradle
        - node_modules
    scripts:
      - name: Set up Android environment
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          
      - name: Install npm dependencies and diagnose
        script: |
          npm install --legacy-peer-deps
          echo "=== DIAGNOSTIC INFO ==="
          echo "Node modules React Native version:"
          ls -la node_modules/ | grep react-native || echo "No react-native in node_modules"
          echo "Package.json contents:"
          cat package.json
          echo "React Native gradle plugin search:"
          find node_modules -name "*react-native-gradle-plugin*" || echo "No gradle plugin found"
          echo "React Native android folder:"
          ls -la node_modules/react-native/ | grep android || echo "No android folder"
          
      - name: Set Android SDK permissions
        script: |
          cd android
          chmod +x gradlew
          
      - name: Create debug keystore
        script: |
          if [ ! -f android/app/debug.keystore ]; then
            keytool -genkeypair -v -keystore android/app/debug.keystore \
              -storepass android -alias androiddebugkey -keypass android \
              -keyalg RSA -keysize 2048 -validity 10000 \
              -dname "CN=Android Debug,O=Android,C=US"
          fi
          
      - name: Try simple Android build without React Native plugin
        script: |
          cd android
          echo "Attempting build with modified gradle files..."
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace
          
    artifacts:
      - android/app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - your.email@example.com # Replace with your email
        notify:
          success: true
          failure: true
