package com.hellohari;

import android.content.Context;
import android.util.Log;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * ScamPatternEngine — shared detection logic driven by {@code patterns.json}.
 *
 * <p>This engine is a direct port of the Python reference implementation in
 * {@code hello-hari-recorder/backend/app/detection/scam_detector.py}. The JSON
 * bundle is generated by {@code scripts/export_patterns_json.py} so both
 * platforms produce identical scores.
 *
 * <p>Loading strategy:
 * <ol>
 *   <li>Read {@code assets/patterns.json} (bundled with the APK).</li>
 *   <li>(Future) optionally overlay a newer bundle fetched from the backend's
 *       {@code /api/patterns.json} endpoint and cached in app files.</li>
 * </ol>
 *
 * <p>The engine is fully offline after load — no network calls are made during
 * {@link #analyze(String)}.
 */
public final class ScamPatternEngine {

    private static final String TAG = "ScamPatternEngine";
    private static final String ASSET_FILE = "patterns.json";

    private static volatile ScamPatternEngine sInstance;

    // ---- Parsed bundle state (immutable after load) ----

    private final int schemaVersion;
    private final String generatedAt;

    private final int riskCap;
    private final double scamThreshold;           // e.g. 0.6
    private final double categoryRepeatBonus;    // e.g. 0.1  (+10% per extra hit)
    private final int scoreCtxThrDem;
    private final int scoreThrDem;
    private final int scoreCtxDem;
    private final int scoreCtxThr;
    private final int stemMinLength;             // e.g. 4

    private final Map<String, Integer> indicatorBonuses;   // tag -> bonus
    private final Map<String, String>  indicatorLabels;    // tag -> label

    /** Ordered list of (id, label, patternMap). */
    private final List<PatternCategory> patternCategories;
    /** Tag -> set of terms. */
    private final Map<String, Set<String>> indicatorSets;
    /** All archetypes. */
    private final List<Archetype> archetypes;

    // ---- Public API ----

    /** Lazily loads from {@code assets/patterns.json}. Thread-safe. */
    public static ScamPatternEngine getInstance(Context ctx) throws IOException, JSONException {
        ScamPatternEngine local = sInstance;
        if (local == null) {
            synchronized (ScamPatternEngine.class) {
                local = sInstance;
                if (local == null) {
                    local = load(ctx.getApplicationContext());
                    sInstance = local;
                }
            }
        }
        return local;
    }

    /**
     * Analyze a transcript. Mirrors {@code analyze_text} from the Python reference.
     *
     * @param text raw transcript (may contain any Indian script or English)
     * @return structured result with risk score, matched labels, explanation,
     *         and raw debug hits.
     */
    public Result analyze(String text) {
        if (text == null || text.trim().isEmpty()) {
            return new Result(false, 0, 0.0, Collections.emptyList(),
                    "No text to analyze.", Collections.emptyList());
        }

        final String lower = text.toLowerCase(Locale.ROOT);
        int totalScore = 0;
        final List<String> detected = new ArrayList<>();
        final Map<String, Integer> categoryScores = new LinkedHashMap<>();

        // Layer 1 — exact phrase matching per category
        for (PatternCategory cat : patternCategories) {
            int catScore = checkPatterns(lower, cat, detected);
            if (catScore > 0) {
                categoryScores.put(cat.id, catScore);
                totalScore += catScore;
            }
        }

        // Layer 2 — keyword co-occurrence across archetypes
        int cooccur = checkKeywordCooccurrence(lower, detected);
        if (cooccur > 0) {
            categoryScores.put("KEYWORD_COOCCUR", cooccur);
            totalScore += cooccur;
        }

        // Cross-language indicator bonuses (each fires at most once)
        totalScore += checkIndicatorSet(lower, "URGENCY", detected);
        totalScore += checkIndicatorSet(lower, "AUTHORITY", detected);
        totalScore += checkIndicatorSet(lower, "FINANCIAL_RISK", detected);
        totalScore += checkIndicatorSet(lower, "TECH_SUPPORT", detected);
        totalScore += checkIndicatorSet(lower, "SECRECY", detected);

        if (totalScore > riskCap) totalScore = riskCap;

        if (totalScore == 0) {
            Log.d(TAG, "score=0 NO_MATCH input=" + snippet(text));
            return new Result(false, 0, 0.0, Collections.emptyList(),
                    "No scam patterns detected.", Collections.emptyList());
        }

        double riskFraction = Math.round((totalScore / 100.0) * 100.0) / 100.0;
        boolean isScam = riskFraction >= scamThreshold;

        // Build human-readable label list (deduplicated, preserving order)
        final LinkedHashSet<String> matchedLabels = new LinkedHashSet<>();
        for (String catId : categoryScores.keySet()) {
            String label = labelForCategory(catId);
            if (label != null) matchedLabels.add(label);
        }
        // Pick up archetype-specific labels from detected[] markers
        for (String d : detected) {
            if (d.startsWith("[KEYWORD_COOCCUR:")) {
                int close = d.indexOf(']');
                if (close > 0) {
                    String tag = d.substring(1, close);       // KEYWORD_COOCCUR:bank_otp
                    String archetypeId = tag.substring("KEYWORD_COOCCUR:".length());
                    String label = labelForArchetype(archetypeId);
                    if (label != null) matchedLabels.add(label);
                }
            }
        }
        // Indicator labels
        for (String tag : INDICATOR_TAGS) {
            String marker = "[" + tag + "]";
            for (String d : detected) {
                if (d.contains(marker)) {
                    matchedLabels.add(indicatorLabels.get(tag));
                    break;
                }
            }
        }

        final List<String> matchedList = new ArrayList<>(matchedLabels);
        final String explanation;
        if (isScam) {
            final String level;
            if (totalScore > 90)       level = "CRITICAL THREAT";
            else if (totalScore > 70)  level = "HIGH RISK";
            else                       level = "SCAM DETECTED";
            explanation = level + " (" + totalScore + "%): Detected "
                    + detected.size() + " scam indicator(s) — "
                    + joinFirst(matchedList, 3);
        } else {
            explanation = "LOW RISK (" + totalScore + "%): Some suspicious patterns — "
                    + joinFirst(matchedList, 2);
        }

        Log.i(TAG, "score=" + totalScore + " scam=" + isScam
                + " hits=" + detected.size() + " input=" + snippet(text));

        return new Result(isScam, totalScore, riskFraction, matchedList, explanation, detected);
    }

    /** Bundle metadata — useful for diagnostics & OTA freshness checks. */
    public int getSchemaVersion()  { return schemaVersion; }
    public String getGeneratedAt() { return generatedAt; }
    public int getPatternCount() {
        int n = 0;
        for (PatternCategory c : patternCategories) n += c.patterns.size();
        return n;
    }

    // ---- Algorithm internals (mirror scam_detector.py / scam_archetypes.py) ----

    private int checkPatterns(String text, PatternCategory cat, List<String> detected) {
        int score = 0;
        int count = 0;
        for (Map.Entry<String, Integer> e : cat.patterns.entrySet()) {
            if (text.contains(e.getKey())) {
                int pts = e.getValue();
                score += pts;
                count += 1;
                detected.add("[" + cat.id + "] " + e.getKey() + " (+" + pts + ")");
            }
        }
        if (count > 1) {
            // int() truncation matches Python — positive, so (int) floor is fine
            score = (int) (score * (1.0 + (count - 1) * categoryRepeatBonus));
        }
        return score;
    }

    private int checkIndicatorSet(String text, String tag, List<String> detected) {
        Set<String> terms = indicatorSets.get(tag);
        Integer bonus = indicatorBonuses.get(tag);
        if (terms == null || bonus == null) return 0;
        for (String term : terms) {
            if (text.contains(term)) {
                detected.add("[" + tag + "] " + term + " (+" + bonus + ")");
                return bonus;
            }
        }
        return 0;
    }

    private int checkKeywordCooccurrence(String lower, List<String> detected) {
        final String[] words = lower.split("\\s+");
        final Set<String> wordSet = new LinkedHashSet<>(Arrays.asList(words));
        final String collapsed = lower.replace(" ", "");
        final String[] collapsedWords = collapsed.split("\\s+");
        final Set<String> collapsedWordSet = new LinkedHashSet<>(Arrays.asList(collapsedWords));

        int best = 0;
        for (Archetype a : archetypes) {
            String ctxHit = matchKeywords(lower, wordSet, a.context);
            String thrHit = matchKeywords(lower, wordSet, a.threat);
            String demHit = matchKeywords(lower, wordSet, a.demand);
            if (demHit == null) {
                demHit = matchKeywords(collapsed, collapsedWordSet, a.demand);
            }

            boolean hasCtx = ctxHit != null;
            boolean hasThr = thrHit != null;
            boolean hasDem = demHit != null;

            int score = 0;
            String detail = null;
            if (hasCtx && hasThr && hasDem) {
                score = scoreCtxThrDem;
                detail = "context(" + ctxHit + ") + threat(" + thrHit
                        + ") + demand(" + demHit + ") (+" + score + ")";
            } else if (hasThr && hasDem) {
                score = scoreThrDem;
                detail = "threat(" + thrHit + ") + demand(" + demHit + ") (+" + score + ")";
            } else if (hasCtx && hasDem) {
                score = scoreCtxDem;
                detail = "context(" + ctxHit + ") + demand(" + demHit + ") (+" + score + ")";
            } else if (hasCtx && hasThr) {
                score = scoreCtxThr;
                detail = "context(" + ctxHit + ") + threat(" + thrHit + ") (+" + score + ")";
            }

            if (detail != null) {
                detected.add("[KEYWORD_COOCCUR:" + a.id + "] " + detail);
            }
            if (score > best) best = score;
        }
        return best;
    }

    private String matchKeywords(String textLower, Set<String> words, Set<String> keywords) {
        for (String kw : keywords) {
            String kwLower = kw.toLowerCase(Locale.ROOT);
            if (textLower.contains(kwLower)) return kw;
            // 4+ char prefix matching (either direction) — matches Python _match_keywords
            if (kwLower.length() >= stemMinLength) {
                for (String w : words) {
                    if (w.length() >= stemMinLength
                            && (w.startsWith(kwLower) || kwLower.startsWith(w))) {
                        return kw;
                    }
                }
            }
        }
        return null;
    }

    // ---- Label lookup ----

    private String labelForCategory(String id) {
        if ("KEYWORD_COOCCUR".equals(id)) {
            // Generic archetype bucket — specific labels are added separately.
            return null;
        }
        for (PatternCategory c : patternCategories) {
            if (c.id.equals(id)) return c.label;
        }
        return indicatorLabels.get(id);
    }

    private String labelForArchetype(String archetypeId) {
        for (Archetype a : archetypes) {
            if (a.id.equals(archetypeId)) return a.label;
        }
        return null;
    }

    // ---- Loader ----

    private static ScamPatternEngine load(Context ctx) throws IOException, JSONException {
        try (InputStream is = ctx.getAssets().open(ASSET_FILE)) {
            String raw = readAll(is);
            JSONObject root = new JSONObject(raw);
            return new ScamPatternEngine(root);
        }
    }

    private ScamPatternEngine(JSONObject root) throws JSONException {
        this.schemaVersion = root.optInt("schema_version", 1);
        this.generatedAt   = root.optString("generated_at", "");

        JSONObject constants = root.getJSONObject("constants");
        this.riskCap              = constants.optInt("risk_cap", 100);
        this.scamThreshold        = constants.optDouble("scam_threshold", 0.6);
        this.categoryRepeatBonus  = constants.optDouble("category_repeat_bonus", 0.1);
        this.stemMinLength        = constants.optInt("stem_match_min_length", 4);

        JSONObject co = constants.getJSONObject("cooccurrence_scores");
        this.scoreCtxThrDem = co.optInt("context_threat_demand", 95);
        this.scoreThrDem    = co.optInt("threat_demand", 80);
        this.scoreCtxDem    = co.optInt("context_demand", 75);
        this.scoreCtxThr    = co.optInt("context_threat", 70);

        // Indicator bonuses & labels
        JSONObject bonuses = root.getJSONObject("indicator_bonuses");
        JSONObject iLabels = root.getJSONObject("indicator_labels");
        Map<String, Integer> bMap = new HashMap<>();
        Map<String, String>  lMap = new HashMap<>();
        for (String tag : INDICATOR_TAGS) {
            bMap.put(tag, bonuses.getInt(tag));
            lMap.put(tag, iLabels.getString(tag));
        }
        this.indicatorBonuses = Collections.unmodifiableMap(bMap);
        this.indicatorLabels  = Collections.unmodifiableMap(lMap);

        // Pattern categories
        JSONArray cats = root.getJSONArray("pattern_categories");
        List<PatternCategory> catList = new ArrayList<>(cats.length());
        for (int i = 0; i < cats.length(); i++) {
            JSONObject c = cats.getJSONObject(i);
            String id = c.getString("id");
            String label = c.getString("label");
            JSONObject pats = c.getJSONObject("patterns");
            LinkedHashMap<String, Integer> pm = new LinkedHashMap<>(pats.length());
            Iterator<String> it = pats.keys();
            while (it.hasNext()) {
                String phrase = it.next();
                pm.put(phrase, pats.getInt(phrase));
            }
            catList.add(new PatternCategory(id, label, Collections.unmodifiableMap(pm)));
        }
        this.patternCategories = Collections.unmodifiableList(catList);

        // Indicator sets
        JSONObject sets = root.getJSONObject("indicator_sets");
        Map<String, Set<String>> setMap = new HashMap<>();
        for (String tag : INDICATOR_TAGS) {
            JSONArray arr = sets.getJSONArray(tag);
            LinkedHashSet<String> terms = new LinkedHashSet<>(arr.length());
            for (int i = 0; i < arr.length(); i++) terms.add(arr.getString(i));
            setMap.put(tag, Collections.unmodifiableSet(terms));
        }
        this.indicatorSets = Collections.unmodifiableMap(setMap);

        // Archetypes
        JSONArray arr = root.getJSONArray("archetypes");
        List<Archetype> aList = new ArrayList<>(arr.length());
        for (int i = 0; i < arr.length(); i++) {
            JSONObject a = arr.getJSONObject(i);
            aList.add(new Archetype(
                    a.getString("id"),
                    a.getString("label"),
                    toLowerSet(a.getJSONArray("context")),
                    toLowerSet(a.getJSONArray("threat")),
                    toLowerSet(a.getJSONArray("demand"))
            ));
        }
        this.archetypes = Collections.unmodifiableList(aList);

        Log.i(TAG, "Loaded schema=" + schemaVersion + " categories=" + patternCategories.size()
                + " phrases=" + getPatternCount() + " archetypes=" + archetypes.size());
    }

    private static Set<String> toLowerSet(JSONArray arr) throws JSONException {
        LinkedHashSet<String> s = new LinkedHashSet<>(arr.length());
        for (int i = 0; i < arr.length(); i++) s.add(arr.getString(i).toLowerCase(Locale.ROOT));
        return Collections.unmodifiableSet(s);
    }

    private static String readAll(InputStream is) throws IOException {
        StringBuilder sb = new StringBuilder(64 * 1024);
        try (BufferedReader r = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8))) {
            char[] buf = new char[8192];
            int n;
            while ((n = r.read(buf)) > 0) sb.append(buf, 0, n);
        }
        return sb.toString();
    }

    private static String joinFirst(List<String> items, int max) {
        StringBuilder sb = new StringBuilder();
        int limit = Math.min(max, items.size());
        for (int i = 0; i < limit; i++) {
            if (i > 0) sb.append(", ");
            sb.append(items.get(i));
        }
        return sb.toString();
    }

    private static String snippet(String s) {
        if (s == null) return "";
        return s.length() <= 120 ? s : s.substring(0, 120);
    }

    private static final String[] INDICATOR_TAGS =
            {"URGENCY", "AUTHORITY", "FINANCIAL_RISK", "TECH_SUPPORT", "SECRECY"};

    // ---- Data classes ----

    private static final class PatternCategory {
        final String id;
        final String label;
        final Map<String, Integer> patterns;
        PatternCategory(String id, String label, Map<String, Integer> patterns) {
            this.id = id; this.label = label; this.patterns = patterns;
        }
    }

    private static final class Archetype {
        final String id;
        final String label;
        final Set<String> context;
        final Set<String> threat;
        final Set<String> demand;
        Archetype(String id, String label, Set<String> c, Set<String> t, Set<String> d) {
            this.id = id; this.label = label; this.context = c; this.threat = t; this.demand = d;
        }
    }

    /** Analysis result — parity with {@code ScamAnalysis} pydantic model. */
    public static final class Result {
        private final boolean isScam;
        private final int riskScore;         // 0-100
        private final double riskFraction;   // 0.0-1.0
        private final List<String> matchedPatterns;
        private final String explanation;
        private final List<String> debugDetails;

        public Result(boolean isScam, int riskScore, double riskFraction,
                      List<String> matchedPatterns, String explanation,
                      List<String> debugDetails) {
            this.isScam = isScam;
            this.riskScore = riskScore;
            this.riskFraction = riskFraction;
            this.matchedPatterns = Collections.unmodifiableList(new ArrayList<>(matchedPatterns));
            this.explanation = explanation;
            this.debugDetails = Collections.unmodifiableList(new ArrayList<>(debugDetails));
        }

        public boolean isScam()                   { return isScam; }
        public int getRiskScore()                 { return riskScore; }
        public double getRiskFraction()           { return riskFraction; }
        public List<String> getMatchedPatterns()  { return matchedPatterns; }
        public String getExplanation()            { return explanation; }
        public List<String> getDebugDetails()     { return debugDetails; }
    }
}
